version: '3'
services:
  todo-list:
    container_name: todolist
    image: adatech/movie-battle:1.0
    ports:
      - 8080
    expose:
      - 8080
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - 8080:8080
    volumes:
      - ./doc/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
